import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import { Logo } from '../components/logo'
import { MapMenuButton } from '../components/map_menu_button'
import { CompanyInfo } from '../layout/company_info'
import { MapView } from '../layout/map'
import { SearchCompany } from '../layout/search_company'
import { MdAutoGraph, MdMenu, MdPersonOutline } from 'react-icons/md'
import { FilterCompany } from '../components/filter_company'
import { useQuery } from 'react-query'
import axios from 'axios'
import { ICompany } from '../types/company'
import useFilterValues from '../hooks/useFilterValues'
import { Profile } from '../layout/profile'

export default function Home() {
  const [activeMarker, setActiveMarker] = useState<number | null>(null)
  const { industriesIds, toggleIndustry, needsIds, productsIds, toggleNeed, toggleProduct } = useFilterValues()
  const [showProfile, toggleProfile] = useState(false)

  const { isLoading, data: companyInfo, error } = useQuery<ICompany>({
    queryKey: 'company' + activeMarker,
    queryFn: async () => {
      const { data } = await axios.get(`/supplinx/company-info/${activeMarker}`)
      console.log(data)
      return data
    },
    enabled: activeMarker !== null
  })


  return (
    <div className='h-screen'>
      <Head>
        <title>supply.us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='fixed left-2 top-2 z-50 w-96'>
        <SearchCompany setActiveMarker={setActiveMarker} activeMarker={activeMarker} />
      </div>
      <div className='fixed left-100 top-2 z-20 pl-2 flex items-start'>
        <FilterCompany toggleIndustry={toggleIndustry} placeholder='Filter by industry' type='industries' />
        <div className="mx-4">
          <FilterCompany toggleIndustry={toggleProduct} placeholder='Filter by offers' type='products' />
        </div>
        <FilterCompany toggleIndustry={toggleNeed} placeholder='Filter by needs' type='needs' />
      </div>
      <div className='fixed right-2 top-2 z-50'>
        <Logo />
      </div>
      <CompanyInfo toggleProfile={toggleProfile.bind(true, true)} visible={activeMarker !== null} activeMarker={activeMarker} data={companyInfo} isLoading={isLoading} />
      <MapView industries={industriesIds} products={productsIds} needs={needsIds} activeMarker={activeMarker} setActiveMarker={setActiveMarker} setCompanyInfoVisible={setActiveMarker.bind(true, null)} selectedCompany={companyInfo} />
      <div className='fixed bottom-0 right-0 pb-5 flex flex-row items-center z-50'>
        <MapMenuButton icon={<MdAutoGraph />} />
        <MapMenuButton icon={<MdPersonOutline />} />
        <MapMenuButton icon={<MdMenu />} />
      </div>
      {true && <Profile id={activeMarker} />}
    </div>
  )
}